### ISSUE TITLE
Crashes on committers that are not GitHub users

### ISSUE THREAD

**Issue by eush77** [kat4/commit4#38]
Tried it on a big repo and the app crashed. (Sorry about that!)
![screenshot](https://cloud.githubusercontent.com/assets/4472489/10944232/451ec57a-8329-11e5-8565-11e2f13183a8.png)

**Comment by eush77** [comment]
It doesn't matter whether repository is big or not (GitHub API pages results anyway).

In this case committer is not a GitHub user and has no login or avatar.

```
/tmp/tmpdir/G95AZH/commit4/githubrequest.js:45
        username: commit.committer.login,
                                  ^

TypeError: Cannot read property 'login' of null
    at addCommitToHistoryObject (/tmp/tmpdir/G95AZH/commit4/githubrequest.js:45:35)
    at Array.forEach (native)
    at /tmp/tmpdir/G95AZH/commit4/githubrequest.js:35:36
    at IncomingMessage.<anonymous> (/tmp/tmpdir/G95AZH/commit4/githubrequest.js:87:7)
    at emitNone (events.js:72:20)
    at IncomingMessage.emit (events.js:166:7)
    at endReadableNT (_stream_readable.js:893:12)
    at doNTCallback2 (node.js:429:9)
    at process._tickCallback (node.js:343:17)
```
